apiVersion: v1
kind: List
metadata: {}
items:
- kind: Pod
  apiVersion: v1
  metadata:
    name: openshift-http-request
    creationTimestamp: 
    labels:
      name: openshift-http-request
  spec:
    containers:
    - name: openshift-http-request
      image: mserrate/openshift-http-request
      ports:
      - containerPort: 8080
        protocol: TCP
      resources: {}
      terminationMessagePath: "/dev/termination-log"
      imagePullPolicy: IfNotPresent
      capabilities: {}
      securityContext:
        capabilities: {}
        privileged: false
    restartPolicy: Always
    dnsPolicy: ClusterFirst
    serviceAccount: ''
  status: {}
- kind: Service
  apiVersion: v1
  metadata: 
    name: openshift-http-request
  spec: 
    ports: 
      - name: agent
        protocol: TCP
        port: 8080
        targetPort: 8080
    selector: 
      name: openshift-http-request
    type: ClusterIP
    sessionAffinity: None